### ISSUE TITLE
[코테] K번째 수

### ISSUE THREAD

**Issue by JungHanLeee** [Team-Discipline/Coding-Test-Proceedings#7]
<html>
<body>
<ul class="challenge-nav nav nav-tabs nav-tabs-dark task-tab" id="tab" role="tablist" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; display: flex; flex-wrap: wrap; padding: 0px 1rem; list-style: none; border-bottom: 0px; box-shadow: rgb(23, 35, 52) 0px -0.0625rem inset; background-color: rgb(38, 55, 71); position: relative; justify-content: space-between; height: 3.5rem; color: rgb(38, 55, 71); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="nav-item algorithm-nav-link algorithm-title" style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-bottom: 0px; padding: 0.9375rem 0px 0.5rem; border-bottom: 3px solid rgb(255, 255, 255); color: white;">K번째수</li><div class="main-section" style="box-sizing: border-box; display: flex; flex-direction: row; height: calc(100vh - 10rem);"><div class="guide-section" id="tour2" style="box-sizing: border-box; overflow-y: auto; padding: 1rem; background-color: rgb(38, 55, 71); width: calc(40% - 12px);"><div class="guide-section-description" style="box-sizing: border-box;"><h6 class="guide-section-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-weight: 700; line-height: 1.5; font-size: 14px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; -webkit-font-smoothing: antialiased;">문제 설명</h6><div class="markdown solarized-dark" style="box-sizing: border-box; background-color: transparent; word-break: normal; overflow-wrap: break-word; color: rgb(178, 192, 204);"><p style="box-sizing: border-box; margin: 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하려 합니다.</p><p style="box-sizing: border-box; margin: 0.75rem 0px 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">예를 들어 array가 [1, 5, 2, 6, 3, 7, 4], i = 2, j = 5, k = 3이라면</p><ol style="box-sizing: border-box; margin: 1rem 0px 0px;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6;">array의 2번째부터 5번째까지 자르면 [5, 2, 6, 3]입니다.</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-top: 0.5rem;">1에서 나온 배열을 정렬하면 [2, 3, 5, 6]입니다.</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-top: 0.5rem;">2에서 나온 배열의 3번째 숫자는 5입니다.</li></ol><p style="box-sizing: border-box; margin: 0.75rem 0px 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, commands의 모든 원소에 대해 앞서 설명한 연산을 적용했을 때 나온 결과를 배열에 담아 return 하도록 solution 함수를 작성해주세요.</p><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">제한사항</h5><ul style="box-sizing: border-box; margin: 0.75rem 0px 0px;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6;">array의 길이는 1 이상 100 이하입니다.</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-top: 0.5rem;">array의 각 원소는 1 이상 100 이하입니다.</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-top: 0.5rem;">commands의 길이는 1 이상 50 이하입니다.</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-top: 0.5rem;">commands의 각 원소는 길이가 3입니다.</li></ul><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">입출력 예</h5>

array | commands | return
-- | -- | --
[1, 5, 2, 6, 3, 7, 4] | [[2, 5, 3], [4, 4, 1], [1, 7, 3]] | [5, 6, 3]

<h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">입출력 예 설명</h5><p style="box-sizing: border-box; margin: 0.75rem 0px 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">[1, 5, 2, 6, 3, 7, 4]를 2번째부터 5번째까지 자른 후 정렬합니다. [2, 3, 5, 6]의 세 번째 숫자는 5입니다.<br style="box-sizing: border-box;">[1, 5, 2, 6, 3, 7, 4]를 4번째부터 4번째까지 자른 후 정렬합니다. [6]의 첫 번째 숫자는 6입니다.<br style="box-sizing: border-box;">[1, 5, 2, 6, 3, 7, 4]를 1번째부터 7번째까지 자릅니다. [1, 2, 3, 4, 5, 6, 7]의 세 번째 숫자는 3입니다.</p></div></div></div></div></div>
</body>
</html>
https://school.programmers.co.kr/learn/courses/30/lessons/42748

**Comment by kreimben** [comment]
문제 링크 좀

**Comment by JungHanLeee** [comment]
수정했어
